---
- hosts: all
  vars:
    devel: chromodoris
    releases:
        - bartholomea
        - "{{ devel }}"
    all_releases:
        - bartholomea
        - "{{ devel }}"
        - staging
    mirror: "http://archive.tanglu.org/tanglu"
    architectures:
        - amd64
        - i386
  sudo: yes
  tasks:
    - apt: update_cache=yes upgrade=dist
    - apt: name=devscripts
    - apt: name=dpkg-dev
    - apt: name=debootstrap
    - apt: name=schroot
    - apt: name=sbuild
    - apt: name=aptitude
    - apt: name=lintian
    - apt: name=haveged
    - apt: name=coreutils

    - user: name=buildd createhome=yes groups=sbuild home=/srv/buildd shell=/bin/bash system=yes
    - file: state=directory path=/srv/buildd/chroots

    - shell: >
        sbuild-createchroot --arch={{ item[1] }}
        --components="main,contrib,non-free"
        --include=aptitude
        --keep-sbuild-chroot-dir
        --make-sbuild-tarball=/srv/buildd/chroots/{{ item[0] }}-{{ item[1] }}.tar.gz
        {{ item[0] }}
        /srv/buildd/chroots/{{ item[0] }}-{{ item[1] }}
        {{ mirror }}
      with_nested:
        - releases
        - architectures
      args:
        creates: /srv/buildd/chroots/{{ item[0] }}-{{ item[1] }}.tar.gz

    - shell: cp -a /srv/buildd/chroots/{{ item[0] }}-{{ item[1] }} /srv/buildd/chroots/staging-{{ item[1] }}
      with_nested:
        - [ "{{ devel }}" ]
        - architectures
      args:
        removes: /srv/buildd/chroots/{{ item[0] }}-{{ item[1] }}

    - shell: find /srv/buildd/chroots/* -maxdepth 0 -type d
      register: sbuild_chroots

    - file: path={{ item }}/dev/ptmx state=absent
      with_items: sbuild_chroots.stdout_lines

    - file: src=pts/ptmx path={{ item }}/dev/ptmx state=link force=yes
      with_items: sbuild_chroots.stdout_lines

    - lineinfile: line=force-unsafe-io dest={{ item }}/etc/dpkg/dpkg.cfg.d/90sbuild create=yes
      with_items: sbuild_chroots.stdout_lines

    - shell: if [ -d /srv/buildd/chroots/{{ item[2] }}-{{ item[1] }} ]; then echo "{{ item[0] }} {{ mirror }} {{ item[2] }}-updates main contrib non-free" >> /srv/buildd/chroots/{{ item[2] }}-{{ item[1] }}/etc/apt/sources.list; fi
      with_nested:
        - [ 'deb', 'deb-src' ]
        - architectures
        - releases

    - shell: if [ -d /srv/buildd/chroots/staging-{{ item[1] }} ]; then echo "{{ item[0] }} {{ mirror }} staging main contrib non-free" >> /srv/buildd/chroots/staging-{{ item[1] }}/etc/apt/sources.list; fi
      with_nested:
        - [ 'deb', 'deb-src' ]
        - architectures

    - shell: mv /etc/schroot/chroot.d/{{ item[0] }}-{{ item[1] }}-sbuild-* /etc/schroot/chroot.d/{{ item[0] }}-{{ item[1] }}
      with_nested:
        - releases
        - architectures
      args:
        creates: /etc/schroot/chroot.d/{{ item[0] }}-{{ item[1] }}

    - shell: cp /etc/schroot/chroot.d/{{ item[0] }}-{{ item[1] }} /etc/schroot/chroot.d/{{ item[0] }}-updates-{{ item[1] }}
      with_nested:
        - releases
        - architectures
      args:
        creates: /etc/schroot/chroot.d/{{ item[0] }}-updates-{{ item[1] }}

    - shell: cp /etc/schroot/chroot.d/{{ devel }}-{{ item }} /etc/schroot/chroot.d/staging-{{ item }}
      with_items: architectures
      args:
        creates: /etc/schroot/chroot.d/staging-{{ item }}

    # disable sources in the build chroots
    - replace: dest={{ item }}/etc/apt/sources.list regexp="^deb-src" replace="#deb-src"
      with_items: sbuild_chroots.stdout_lines

    - replace: dest=/etc/schroot/chroot.d/{{ item[0] }}-{{ item[1] }} regexp="{{ item[0] }}-{{ item[1] }}-sbuild" replace="{{ item[0] }}-{{ item[1] }}"
      with_nested:
        - releases
        - architectures

    - replace: dest=/etc/schroot/chroot.d/{{ item[0] }}-updates-{{ item[1] }} regexp="{{ item[0] }}-{{ item[1] }}-sbuild" replace="{{ item[0] }}-updates-{{ item[1] }}"
      with_nested:
        - releases
        - architectures

    - replace: dest=/etc/schroot/chroot.d/staging-{{ item }} regexp="{{ devel }}-{{ item }}-sbuild" replace="staging-{{ item }}"
      with_items: architectures

    - replace: dest=/etc/schroot/chroot.d/staging-{{ item }} regexp="{{ devel }}" replace="staging"
      with_items: architectures

    # workaround for https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=769289
    - lineinfile: dest=/etc/schroot/chroot.d/staging-{{ item }} line="profile=sbuild"
      with_items: architectures

    - shell: tar caf /srv/buildd/chroots/{{ item[0] }}-{{ item[1] }}.tar.gz -C /srv/buildd/chroots/{{ item[0] }}-{{ item[1] }} . && rm -r /srv/buildd/chroots/{{ item[0] }}-{{ item[1] }}
      with_nested:
        - all_releases
        - architectures
      args:
        removes: /srv/buildd/chroots/{{ item[0] }}-{{ item[1] }}

    - shell: schroot --directory /tmp -c source:{{ item[0] }}-{{ item[1] }} -u root -- apt-get -y install eatmydata && touch /srv/buildd/.ansible-{{ item[0] }}-{{ item[1] }}-eatmydata-installed
      with_nested:
        - all_releases
        - architectures
      args:
        creates: /srv/buildd/.ansible-{{ item[0] }}-{{ item[1] }}-eatmydata-installed

    - lineinfile: dest=/etc/schroot/chroot.d/{{ item[0] }}-{{ item[1] }} line="command-prefix=eatmydata"
      with_nested:
        - all_releases
        - architectures

    - shell: sbuild-update --update --upgrade --clean {{ item[0] }}-{{ item[1] }}
      with_nested:
        - all_releases
        - architectures

    - name: Get the available CPU count
      shell: nproc
      register: ncores

    - template: dest=/etc/sbuild/sbuild.conf src=sbuild/sbuild.conf.j2
      with_items:
        - { ncores: "{{ ncores.stdout }}" }

    - file: state=directory path=/srv/buildd/.gnupg/ group=buildd owner=buildd
    - shell: haveged & sudo -H -u buildd sbuild-update --keygen
