---
- hosts: all
  vars:
    devel: dasyatis
    releases:
        - bartholomea
        - chromodoris
        - "{{ devel }}"
        - staging
    mirror: "http://archive.tanglu.org/tanglu"
    architectures:
        - amd64
        - i386
    btrfs: False # experimental
  sudo: yes
  tasks:
    - apt: update_cache=yes upgrade=dist
    - apt: name=devscripts
    - apt: name=dpkg-dev
    - apt: name=debootstrap
    - apt: name=schroot
    - apt: name=sbuild
    - apt: name=aptitude
    - apt: name=lintian
    - apt: name=haveged
    - apt: name=coreutils

    - apt: name=btrfs-tools
      when: btrfs

    - user: name=buildd createhome=yes groups=sbuild home=/srv/buildd shell=/bin/bash system=yes

    - file: state=directory path=/srv/buildd/chroots

    - file: state=directory path=/srv/buildd/snapshots
      when: btrfs

    - shell: btrfs subvolume create /srv/buildd/chroots/{{ item[0] }}-{{ item[1] }}
      with_nested:
        - releases
        - architectures
      args:
        creates: /srv/buildd/chroots/{{ item[0] }}-{{ item[1] }}
      when: btrfs

    - shell: >
        sbuild-createchroot --arch={{ item[1] }}
        --components="main,contrib,non-free"
        --include=aptitude
        --keep-sbuild-chroot-dir
        --make-sbuild-tarball=/srv/buildd/chroots/{{ item[0] }}-{{ item[1] }}.tar.gz
        {{ item[0] }}
        /srv/buildd/chroots/{{ item[0] }}-{{ item[1] }}
        {{ mirror }}
      with_nested:
        - releases
        - architectures
      args:
        creates: /srv/buildd/chroots/{{ item[0] }}-{{ item[1] }}.tar.gz
      when: not btrfs

    - shell: >
        sbuild-createchroot --arch={{ item[1] }}
        --components="main,contrib,non-free"
        --include=aptitude
        {{ item[0] }}
        /srv/buildd/chroots/{{ item[0] }}-{{ item[1] }}
        {{ mirror }}
      with_nested:
        - releases
        - architectures
      args:
        creates: /srv/buildd/chroots/{{ item[0] }}-{{ item[1] }}/tmp
      when: btrfs

    - file: state=directory path=/srv/buildd/chroots/{{ item[0] }}-{{ item[1] }}
      with_nested:
        - releases
        - architectures

    # unpack any existing chroots
    - shell: >
        if [ -e /srv/buildd/chroots/{{ item[0] }}-{{ item[1] }}.tar.gz ]; then
        tar xf /srv/buildd/chroots/{{ item[0] }}-{{ item[1] }}.tar.gz -C /srv/buildd/chroots/{{ item[0] }}-{{ item[1] }};
        rm /srv/buildd/chroots/{{ item[0] }}-{{ item[1] }}.tar.gz;
        fi
      with_nested:
        - releases
        - architectures
      when: not btrfs

    - file: path=/srv/buildd/chroots/{{ item[0] }}-{{ item[1] }}/dev/ptmx state=absent
      with_nested:
        - releases
        - architectures

    - file: src=pts/ptmx path=/srv/buildd/chroots/{{ item[0] }}-{{ item[1] }}/dev/ptmx state=link force=yes
      with_nested:
        - releases
        - architectures

    - lineinfile: line=force-unsafe-io dest=/srv/buildd/chroots/{{ item[0] }}-{{ item[1] }}/etc/dpkg/dpkg.cfg.d/90sbuild create=yes
      with_nested:
        - releases
        - architectures

    - lineinfile: line='Acquire::PDiffs "false";' dest=/srv/buildd/chroots/{{ item[0] }}-{{ item[1] }}/etc/apt/apt.conf.d/00pdiff create=yes
      with_nested:
        - releases
        - architectures

    - lineinfile: line="{{ item[0] }} {{ mirror }} {{ item[2] }}-updates main contrib non-free" dest=/srv/buildd/chroots/{{ item[2] }}-{{ item[1] }}/etc/apt/sources.list
      when: item[2] != 'staging'
      with_nested:
        - [ 'deb', '#deb-src' ]
        - architectures
        - releases

    - lineinfile: line="{{ item[0] }} http://buildd.tanglu.net/build-queues buildq-staging main contrib non-free" dest=/srv/buildd/chroots/staging-{{ item[1] }}/etc/apt/sources.list
      with_nested:
        - [ 'deb', '#deb-src' ]
        - architectures

    - shell: mv /etc/schroot/chroot.d/{{ item[0] }}-{{ item[1] }}-sbuild-* /etc/schroot/chroot.d/{{ item[0] }}-{{ item[1] }}
      with_nested:
        - releases
        - architectures
      args:
        creates: /etc/schroot/chroot.d/{{ item[0] }}-{{ item[1] }}

    - replace: dest=/etc/schroot/chroot.d/{{ item[0] }}-{{ item[1] }} regexp="^type=directory" replace="type=btrfs-snapshot"
      with_nested:
        - releases
        - architectures
      when: btrfs

    - replace: dest=/etc/schroot/chroot.d/{{ item[0] }}-{{ item[1] }} regexp="^directory=.*$" replace="btrfs-source-subvolume=/srv/buildd/chroots/{{ item[0] }}-{{ item[1] }}"
      with_nested:
        - releases
        - architectures
      when: btrfs

    - lineinfile: dest=/etc/schroot/chroot.d/{{ item[0] }}-{{ item[1] }} line="btrfs-snapshot-directory=/srv/buildd/snapshots"
      with_nested:
        - releases
        - architectures
      when: btrfs

    - shell: cp /etc/schroot/chroot.d/{{ item[0] }}-{{ item[1] }} /etc/schroot/chroot.d/{{ item[0] }}-updates-{{ item[1] }}
      when: item[0] != 'staging'
      with_nested:
        - releases
        - architectures
      args:
        creates: /etc/schroot/chroot.d/{{ item[0] }}-updates-{{ item[1] }}

    # disable sources in the build chroots
    - replace: dest=/srv/buildd/chroots/{{ item[0] }}-{{ item[1] }}/etc/apt/sources.list regexp="^deb-src" replace="#deb-src"
      with_nested:
        - releases
        - architectures

    - replace: dest=/etc/schroot/chroot.d/{{ item[0] }}-{{ item[1] }} regexp="{{ item[0] }}-{{ item[1] }}-sbuild" replace="{{ item[0] }}-{{ item[1] }}"
      with_nested:
        - releases
        - architectures

    - replace: dest=/etc/schroot/chroot.d/{{ item[0] }}-updates-{{ item[1] }} regexp="{{ item[0] }}-{{ item[1] }}-sbuild" replace="{{ item[0] }}-updates-{{ item[1] }}"
      when: item[0] != 'staging'
      with_nested:
        - releases
        - architectures

    # workaround for https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=769289
    - lineinfile: dest=/etc/schroot/chroot.d/staging-{{ item }} line="profile=sbuild"
      with_items: architectures

    - shell: tar caf /srv/buildd/chroots/{{ item[0] }}-{{ item[1] }}.tar.gz -C /srv/buildd/chroots/{{ item[0] }}-{{ item[1] }} . && rm -r /srv/buildd/chroots/{{ item[0] }}-{{ item[1] }}
      with_nested:
        - releases
        - architectures
      args:
        removes: /srv/buildd/chroots/{{ item[0] }}-{{ item[1] }}
      when: not btrfs

    - shell: schroot --directory /tmp -c source:{{ item[0] }}-{{ item[1] }} -u root -- apt-get -y install eatmydata
      with_nested:
        - releases
        - architectures

    - lineinfile: dest=/etc/schroot/chroot.d/{{ item[0] }}-{{ item[1] }} line="command-prefix=eatmydata"
      with_nested:
        - releases
        - architectures

    - shell: sbuild-update --update --upgrade --clean {{ item[0] }}-{{ item[1] }}
      with_nested:
        - releases
        - architectures

    - name: Get the available CPU count
      shell: nproc
      register: ncores

    - template: dest=/etc/sbuild/sbuild.conf src=sbuild/sbuild.conf.j2
      with_items:
        - { ncores: "{{ ncores.stdout }}" }

    - file: state=directory path=/srv/buildd/.gnupg/ group=buildd owner=buildd
    - shell: haveged & sudo -H -u buildd sbuild-update --keygen
